SELECT   DEPARTMENT_ID,  LAST_NAME, SALARY,
 RANK( ) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) DEPT_RANK,
 RANK( ) OVER (ORDER BY SALARY DESC) ALL_RANK     
FROM    EMP
ORDER BY DEPARTMENT_ID, SALARY DESC;

SELECT  LAST_NAME, SALARY
 , RANK( )              OVER (ORDER BY SALARY DESC) RANK
 , DENSE_RANK( )   OVER (ORDER BY SALARY DESC) DENSE_RANK
FROM   EMP; 

SELECT   JOB_ID, LAST_NAME, SALARY 
 , RANK( )              OVER (ORDER BY SALARY DESC) RANK
 , ROW_NUMBER()  OVER (ORDER BY SALARY DESC) ROW_NUMBER
FROM    EMP; 


SELECT   DEPARTMENT_ID, LAST_NAME, SALARY
  , ROUND( AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID)  , 0) DEPT_AVG
  , SALARY - ROUND( AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID)  , 0) DIFF
FROM    EMP ;

SELECT   DEPARTMENT_ID, LAST_NAME, SALARY
 , MAX(SALARY) OVER (PARTITION BY DEPARTMENT_ID)  DEPT_MAX
FROM    EMP;


SELECT   LAST_NAME, SALARY
 , COUNT(*) OVER (ORDER BY SALARY RANGE BETWEEN 50 PRECEDING AND 150 FOLLOWING) as SIM_CNT
FROM    EMP; 


SELECT   LAST_NAME, SALARY
    , ROUND(RATIO_TO_REPORT(SALARY) OVER (),  2) as R_R 
FROM    EMP ;

SELECT    DEPARTMENT_ID, LAST_NAME, SALARY
    , PERCENT_RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY) as P_R 
FROM     EMP;

SELECT  LAST_NAME, SALARY
          , NTILE(4) OVER (ORDER BY SALARY DESC) as QUAR_TILE 
FROM   EMP ;


