CREATE TABLE EMP
AS
SELECT * FROM HR.EMP;

SELECT * FROM EMP;

DESC EMP;

SELECT LAST_NAME, SALARY
FROM EMP;
-- 설명입니다 
SELECT *
FROM EMP;

SELECT LAST_NAME, SALARY, SALARY * 12
FROM EMP;

SELECT LAST_NAME, SALARY, SALARY * 12 AS YEAR_SALARY
FROM EMP;

SELECT FIRST_NAME || ' ' || LAST_NAME
FROM EMP;


SELECT LAST_NAME, SALARY, 
    SALARY * COMMISSION_PCT AS,
    SALARY + (SALARY * NVL(COMMISSION_PCT, 0)) AS
FROM EMP;

SELECT LAST_NAME, SALARY
FROM EMP
ORDER BY SALARY DESC;


SELECT LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMP
ORDER BY DEPARTMENT_ID, SALARY DESC;


SELECT LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMP
ORDER BY 2,3 DESC;


SELECT LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMP
ORDER BY HIRE_DATE DESC;

SELECT LAST_NAME, SALARY
FROM EMP
WHERE SALARY >= 10000
ORDER BY 2 DESC;

SELECT LAST_NAME, SALARY
FROM EMP
WHERE LAST_NAME = 'Abel';

SELECT LAST_NAME, SALARY, HIRE_DATE
FROM EMP
WHERE HIRE_DATE >= '2005-01-01' ;


SELECT LAST_NAME, SALARY, HIRE_DATE
FROM EMP
WHERE HIRE_DATE >= TO_DATE( '2005-01-01', 'YYYY-MM-DD');


SELECT DISTINCT DEPARTMENT_ID
FROM EMP;


SELECT LAST_NAME, SALARY
FROM EMP
WHERE SALARY >= 10000 AND SALARY <= 15000;

SELECT LAST_NAME, SALARY
FROM EMP
WHERE SALARY BETWEEN 10000 AND 15000;


SELECT LAST_NAME, SALARY, HIRE_DATE
FROM EMP
WHERE HIRE_DATE BETWEEN '2005-01-01' AND '2005-12-30';


SELECT LAST_NAME, SALARY
FROM EMP
WHERE LAST_NAME LIKE  'A%';

SELECT LAST_NAME, SALARY
FROM EMP
WHERE LAST_NAME LIKE   '____';

SELECT LAST_NAME, SALARY
FROM EMP
WHERE LAST_NAME LIKE   '%a__';


SELECT *
FROM EMP
WHERE COMMISSION_PCT IS NOT NULL;

SELECT LAST_NAME, SALARY
FROM EMP
WHERE SALARY >= 10000 ;


SELECT first_name, LAST_NAME, HIRE_DATE
FROM EMP
WHERE HIRE_DATE BETWEEN '2004-01-01' AND '2004-12-31' ;

SELECT FIRST_NAME, COMMISSION_PCT, SALARY, HIRE_DATE
FROM EMP
WHERE  COMMISSION_PCT IS NOT NULL;

SELECT LAST_NAME, SALARY
FROM EMP
WHERE LAST_NAME LIKE  '__a%';

SELECT LAST_NAME, DEPARTMENT_ID
FROM EMP
WHERE DEPARTMENT_ID IN ( S,S);


SELECT LAST_NAME, JOB_ID, SALARY
FROM EMP
WHERE JOB_ID LIKE '%CLERK%' AND SALARY NOT IN (1000, 3000, 5000);

SELECT LAST_NAME, SALARY, 
    SALARY + COMMISSION_PCT AS,
    SALARY * (SALARY / NVL(COMMISSION_PCT, 0.10))  AS
FROM EMP;

SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMP
WHERE  SALARY + (SALARY * COMMISSION_PCT) > SALARY +(SALARY * 0.10);


SELECT *
FROM EMP
WHERE MANAGER_ID IS NULL;


SELECT  EMPLOYEE_ID,LAST_NAME,DEPARTMENT_ID
FROM EMP
WHERE  EMPLOYEE_ID IN (100);


SELECT LAST_NAME, SALARY
FROM EMP
WHERE SALARY >= 15000 AND SALARY <= 22000;


SELECT LAST_NAME, DEPARTMENT_ID, SALARY,EMPLOYEE_ID
FROM EMP
WHERE  DEPARTMENT_ID IN (10,30) ;
